#ifndef LINE_SENSOR_CONFIG_H
#define LINE_SENSOR_CONFIG_H

#include "driver/gpio.h"

#define LINE_SENSOR_QTR_COUNT 8

#define LINE_SENSOR_QTR_1_GPIO GPIO_NUM_6
#define LINE_SENSOR_QTR_2_GPIO GPIO_NUM_16
#define LINE_SENSOR_QTR_3_GPIO GPIO_NUM_7
#define LINE_SENSOR_QTR_4_GPIO GPIO_NUM_8
#define LINE_SENSOR_QTR_5_GPIO GPIO_NUM_9
#define LINE_SENSOR_QTR_6_GPIO GPIO_NUM_10
#define LINE_SENSOR_QTR_7_GPIO GPIO_NUM_11
#define LINE_SENSOR_QTR_8_GPIO GPIO_NUM_15

#define LINE_SENSOR_REVERSE_ORDER 0
#define LINE_SENSOR_READ_TARGET_HZ 1500
#define LINE_SENSOR_READ_PERIOD_US (1000000 / LINE_SENSOR_READ_TARGET_HZ)
#define LINE_SENSOR_MAPPING_READ_TARGET_HZ 750
#define LINE_SENSOR_MAPPING_READ_PERIOD_US 1333
#define LINE_SENSOR_CALIBRATION_DEFAULT_MS 5000
#define LINE_SENSOR_QTR_TIMEOUT_US 300
#define LINE_SENSOR_QTR_TIMEOUT_MARGIN_US 20
#define LINE_SENSOR_QTR_MIN_TIMEOUT_US 80
#define LINE_SENSOR_QTR_NO_RESPONSE_TIMEOUT_US 80
#define LINE_SENSOR_QTR_NO_RESPONSE_STREAK_SAMPLES (LINE_SENSOR_READ_TARGET_HZ / 2)
#define LINE_SENSOR_QTR_NO_RESPONSE_PROBE_INTERVAL 64
#define LINE_SENSOR_QTR_CHARGE_US 10
#define LINE_SENSOR_RAW_SAMPLES 1
#define LINE_SENSOR_VALUE_FILTER_ALPHA_Q8 16
#define LINE_SENSOR_POSITION_FILTER_ALPHA_Q8 12
#define LINE_SENSOR_FILTER_PERCENT_DEFAULT 100
#define LINE_SENSOR_FILTER_PERCENT_MAX 100
#define LINE_SENSOR_POSITION_VALUE_FLOOR 100
#define LINE_SENSOR_POSITION_VISIBLE_THRESHOLD 250
#define LINE_SENSOR_TASK_CORE_ID 0
#define LINE_SENSOR_TASK_PRIORITY 18

#endif
