#ifndef IMU_CONFIG_H
#define IMU_CONFIG_H

#include "driver/gpio.h"
#include "driver/i2c_master.h"

#define IMU_MPU9250_SDA_GPIO GPIO_NUM_17
#define IMU_MPU9250_SCL_GPIO GPIO_NUM_18
#define IMU_I2C_PORT I2C_NUM_0
#define IMU_I2C_FREQ_HZ 50000
#define IMU_MPU9250_ADDR 0x68
#define IMU_AK8963_ADDR 0x0C

#define IMU_SAMPLE_PERIOD_US 4000
#define IMU_TASK_PRIORITY 19
#define IMU_TASK_CORE_ID 1
#define IMU_GYRO_CONFIG_VALUE 0x18
#define IMU_GYRO_LSB_PER_DPS 16.4f
#define IMU_COMPLEMENTARY_ALPHA 0.96f
#define IMU_ROLL_SIGN (-1.0f)
#define IMU_PITCH_SIGN (1.0f)
#define IMU_MAG_YAW_CORRECTION_GAIN 0.02f
#define IMU_MAG_YAW_CORRECTION_GAIN_MIN 0.0f
#define IMU_MAG_YAW_CORRECTION_GAIN_MAX 0.20f
#define IMU_MAG_HEADING_MODE_XY 0
#define IMU_MAG_HEADING_MODE_XZ 1
#define IMU_MAG_HEADING_MODE_YZ 2
#define IMU_MAG_HEADING_MODE_DEFAULT IMU_MAG_HEADING_MODE_XZ
#define IMU_MAG_IGNORED_DEFAULT 1
#define IMU_ACCEL_GYRO_CALIBRATION_DEFAULT_MS 5000
#define IMU_YAW_DRIFT_CALIBRATION_DEFAULT_MS 20000
#define IMU_STATIONARY_GYRO_THRESHOLD_DPS 1.5f
#define IMU_STATIONARY_ACCEL_DELTA_MPS2 0.45f
#define IMU_GYRO_BIAS_AUTO_ALPHA 0.002f
#define IMU_YAW_DRIFT_THRESHOLD_DPS 0.05f
#define IMU_YAW_DRIFT_THRESHOLD_MIN_DPS 0.0f
#define IMU_YAW_DRIFT_THRESHOLD_MAX_DPS 5.0f
#define IMU_MAG_CALIBRATION_DEFAULT_MS 30000
#define IMU_MAG_CALIBRATION_MIN_SAMPLES 600
#define IMU_MAG_CALIBRATION_MIN_AXIS_SPAN_UT 20.0f
#define IMU_MAG_FIELD_MIN_UT 10.0f
#define IMU_MAG_FIELD_MAX_UT 90.0f
#define IMU_MAG_DECLINATION_DEG (-22.96f)

#define IMU_SENSOR_X_TO_ROBOT_X 0.0f
#define IMU_SENSOR_Y_TO_ROBOT_X 1.0f
#define IMU_SENSOR_Z_TO_ROBOT_X 0.0f
#define IMU_SENSOR_X_TO_ROBOT_Y (-1.0f)
#define IMU_SENSOR_Y_TO_ROBOT_Y 0.0f
#define IMU_SENSOR_Z_TO_ROBOT_Y 0.0f
#define IMU_SENSOR_X_TO_ROBOT_Z 0.0f
#define IMU_SENSOR_Y_TO_ROBOT_Z 0.0f
#define IMU_SENSOR_Z_TO_ROBOT_Z 1.0f

#define IMU_MAG_SENSOR_X_TO_MPU_X 0.0f
#define IMU_MAG_SENSOR_Y_TO_MPU_X 1.0f
#define IMU_MAG_SENSOR_Z_TO_MPU_X 0.0f
#define IMU_MAG_SENSOR_X_TO_MPU_Y (-1.0f)
#define IMU_MAG_SENSOR_Y_TO_MPU_Y 0.0f
#define IMU_MAG_SENSOR_Z_TO_MPU_Y 0.0f
#define IMU_MAG_SENSOR_X_TO_MPU_Z 0.0f
#define IMU_MAG_SENSOR_Y_TO_MPU_Z 0.0f
#define IMU_MAG_SENSOR_Z_TO_MPU_Z 1.0f

#endif
