#ifndef CONTROL_CONFIG_H
#define CONTROL_CONFIG_H

#define CONTROL_TASK_PERIOD_US 500
#define CONTROL_TASK_TARGET_HZ 2000.0f
#define CONTROL_TASK_CORE_ID 1
#define CONTROL_TASK_PRIORITY 21
#define CONTROL_RACE_PLAN_TASK_PERIOD_US 1000
#define CONTROL_RACE_PLAN_TASK_TARGET_HZ 1000.0f
#define CONTROL_RACE_PLAN_TASK_CORE_ID CONTROL_TASK_CORE_ID
#define CONTROL_RACE_PLAN_TASK_PRIORITY 19
#define CONTROL_TRACK_ODOMETRY_TASK_PERIOD_US 1000
#define CONTROL_TRACK_ODOMETRY_TASK_TARGET_HZ 1000.0f
#define CONTROL_TRACK_ODOMETRY_TASK_CORE_ID CONTROL_TASK_CORE_ID
#define CONTROL_TRACK_ODOMETRY_TASK_PRIORITY 20
#define CONTROL_TARGET_REACHED_DISTANCE_M 0.06f
#define CONTROL_HEADING_KP_PERCENT_PER_RAD 35.0f
#define CONTROL_HEADING_KI_PERCENT_PER_RAD_S 0.0f
#define CONTROL_HEADING_KD_PERCENT_S_PER_RAD 0.0f
#define CONTROL_LINE_MAX_ERROR_POSITION 3500.0f
#define CONTROL_LINE_MAX_CORRECTION_PERCENT 100.0f
#define CONTROL_LINE_DERIVATIVE_FILTER_ALPHA 0.15f
#define CONTROL_LINE_DT_MIN_S 0.00005f
#define CONTROL_LINE_DT_MAX_S 0.10f
#define CONTROL_MAX_PID_GAIN 1000.0f
#define CONTROL_MAX_STEER_PERCENT 100.0f
#define CONTROL_MAX_INTEGRAL_RAD_S 2.0f
#define CONTROL_INTEGRAL_RESET_ERROR_RAD 0.001f
#define CONTROL_DEFAULT_MOTOR_LIMIT_PERCENT 100
#define CONTROL_SPEED_PROFILE_POINTS 5
#define CONTROL_RACE_PLAN_MAX_SEGMENTS 64
#define CONTROL_RACE_PLAN_CHUNK_MAX_SEGMENTS 10
#define CONTROL_SPEED_AVG_WINDOW_MS 300
#endif
