#ifndef ODOMETRY_CONFIG_H
#define ODOMETRY_CONFIG_H

#include "encoder_config.h"

#define ODOMETRY_WHEEL_DIAMETER_M 0.032f
#define ODOMETRY_PI_F 3.14159265f
#define ODOMETRY_WHEEL_CIRCUMFERENCE_M (ODOMETRY_WHEEL_DIAMETER_M * ODOMETRY_PI_F)
#define ODOMETRY_ENCODER_COUNTS_PER_WHEEL_REV ENCODER_COUNTS_PER_OUTPUT_REV
#define ODOMETRY_TRACK_WIDTH_M 0.117f
#define ODOMETRY_UPDATE_TARGET_HZ 1000
#define ODOMETRY_UPDATE_PERIOD_US (1000000 / ODOMETRY_UPDATE_TARGET_HZ)
#define ODOMETRY_FUSION_IMU_GAIN 0.08f
#define ODOMETRY_MAX_WHEEL_SPEED_MPS 8.0f
#define ODOMETRY_SPIKE_MARGIN_M 0.02f
#define ODOMETRY_MAX_WHEEL_STEP_M 0.20f
#define ODOMETRY_MAX_HEADING_STEP_RAD 1.20f

#endif
