#ifndef RGB_LED_CONFIG_H
#define RGB_LED_CONFIG_H

#include "driver/gpio.h"

#define RGB_LED_GPIO GPIO_NUM_48
#define RGB_LED_RMT_RESOLUTION_HZ 10000000
#define RGB_LED_UPDATE_PERIOD_MS 200
#define RGB_LED_DEFAULT_INTENSITY 32
#define RGB_LED_BATTERY_ALERT_FALLBACK_PERCENT 10.0f
#define RGB_LED_TASK_CORE_ID 0
#define RGB_LED_TASK_PRIORITY 2

#endif
