#ifndef MEMORY_CONFIG_H
#define MEMORY_CONFIG_H

#define MEMORY_NVS_NAMESPACE "robot"
#define MEMORY_MAP_MAX_COUNT 5
#define MEMORY_MAP_NAME_MAX_LEN 15
#define MEMORY_MAP_MAX_POINTS 2048
#define MEMORY_MAP_CHUNK_MAX_POINTS 12

#endif
