#ifndef BATTERY_LEVEL_CONFIG_H
#define BATTERY_LEVEL_CONFIG_H

#include "driver/gpio.h"
#include "esp_adc/adc_oneshot.h"

#define BATTERY_LEVEL_ADC_GPIO GPIO_NUM_13
#define BATTERY_LEVEL_ADC_UNIT ADC_UNIT_2
#define BATTERY_LEVEL_ADC_CHANNEL ADC_CHANNEL_2
#define BATTERY_LEVEL_ADC_ATTEN ADC_ATTEN_DB_12
#define BATTERY_LEVEL_ADC_BITWIDTH ADC_BITWIDTH_DEFAULT

#define BATTERY_LEVEL_RAW_MIN 2500
#define BATTERY_LEVEL_RAW_MAX 3010
#define BATTERY_LEVEL_VOLTAGE_MAX_V 12.6f
#define BATTERY_LEVEL_ADC_REFERENCE_V 3.3f
#define BATTERY_LEVEL_VOLTAGE_SCALE (BATTERY_LEVEL_VOLTAGE_MAX_V * 4095.0f / (BATTERY_LEVEL_RAW_MAX * BATTERY_LEVEL_ADC_REFERENCE_V))
#define BATTERY_LEVEL_SAMPLE_PERIOD_MS 100
#define BATTERY_LEVEL_AVERAGE_PERIOD_MS 2000
#define BATTERY_LEVEL_TASK_CORE_ID 1
#define BATTERY_LEVEL_TASK_PRIORITY 5
#define BATTERY_LEVEL_TASK_STACK_SIZE 4096

#endif
